name: CashShop
main: com.github.nicks.CashShop
author: nicks

version: 1.0
api-version: 1.19

commands:
  캐시:
    description: 메인 캐시 명령어
    aliases: [cash, 보유캐시]
  캐시상점:
    description: 캐시 상점 명령어
    aliases: [cashshop, 캐시샵]